//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubjectSchedule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubjectSchedule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20GOZW;Laboratorija za MRS;20;false;false;false;GGEZPZ;W
        ///30GIZV;Laboratorija za ISA;30;true;true;ture;PZMW20;W
        ///10ZXXY;Sala za eksperimente;10;true;true;false;EXLZ10;L
        ///01NNM;Sala za prezentacije;20;true;true;true;FFHJ10;W
        ///02NNK;Laboratorija za matematiku;20;false;true;false;KKKNM;W
        ///03NNL;Laboratorija za fiziku;20;true;true;true;KKKJJJ;L
        ///04RTR;Laboratorija za elektrotehniku;15;true;true;false;WPPW;W
        ///05RTR;Sala za pisanu i govornu komunikaciju;20;true;false;false;PIGU;W
        ///06OOJ;Sala za algebru;20;false;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string classrooms {
            get {
                return ResourceManager.GetString("classrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.ComponentModel;
        ///
        ///namespace SubjectSchedule
        ///{
        ///    public class Subject : INotifyPropertyChanged
        ///    {
        ///        public event PropertyChangedEventHandler PropertyChanged;
        ///        protected virtual void OnPropertyChanged(string Label)
        ///        {
        ///            if (PropertyChanged != null)
        ///            {
        ///                PropertyChanged(this, new PropertyChangedEventArgs(Label [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
    }
}
